name: spacex_api
description: A Dart api client for the spacex api.
version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  equatable: ^2.0.5
  http: ^0.13.5
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  coverage: ^1.5.0
  json_serializable: ^6.3.1
  meta: ^1.7.0
  test: ^1.21.4
  very_good_analysis: ^3.0.1
  mocktail: ^0.3.0
