name: rocket_repository
description: A dart package for rocket domain.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  spacex_api:
    path: ../spacex_api

dev_dependencies: 
  coverage: ^1.5.0
  mocktail: ^0.3.0
  test: ^1.21.5
  very_good_analysis: ^3.0.1
